export const projects = [
  {
    slug: "gadget-management-server",
    cover: "/projects/gadget.png",
    featured: true,
    learning: true,
    category: "BACKEND",
    name: "Gadget Management Server",
    live_link: "",
    associated_with: "none",
    client_code_link: "",
    server_code_link:
      "https://github.com/farhanhasindipro25/gadget-management-server",
    doc_link: "https://gadget-management-server-ten.vercel.app/docs",
    role: "",
    tech_stack: [
      "Typescript",
      "ExpressJS",
      "MongoDB",
      "Mongoose",
      "Zod",
      "ESLint",
      "Prettier",
      "Husky",
      "Winston",
      "Lint-Staged",
    ],
    details: {
      project_description: "Gadget Management Server",
      features: [
        "User Creation (POST)",
        "User Login (POST)",
        "Add New Electric Gadget (POST)",
        "Delete Electric Gadget (DELETE)",
        "Edit Electric Gadget (PATCH)",
        "View Electric Gadgets List (GET)",
        "View Electric Gadgets Details (GET)",
        "Search, Sort and Filter Gadgets (GET)",
        "BULK Delete Selected Electric Gadgets (DELETE)",
        "List of products to sell (GET)",
        "Sell Product (POST)",
        "Sales History (GET)",
        "Search Sale Information (GET)",
        "Edit Sale Information (PATCH)",
        "Delete Sale Information (DELETE)",
      ],
    },
  },
  {
    slug: "banking-console-app",
    cover: "/projects/console-app/image1.png",
    featured: false,
    learning: true,
    category: "OOP",
    name: "Console Banking Application",
    live_link: "",
    associated_with: "none",
    client_code_link: "",
    server_code_link:
      "https://github.com/farhanhasindipro25/banking-console-application-js",
    doc_link: "",
    role: "",
    tech_stack: ["Javascript", "OOP"],
    details: {
      project_description:
        "A simple banking application. A bank can have several types of accounts say current account, saving account, salary account etc. An account will have fields like name, number, creation date and balance etc. After starting the application, users will have 8 different choices as input from 1 to 8 through the console.",
      features: [
        "Create a new account",
        "Display all accounts",
        "Update an account",
        "Delete an account",
        "Deposit an amount into your account",
        "Withdraw an amount from your account",
        "Search for account",
        "Exit",
      ],
    },
  },
  {
    slug: "pro-hr",
    featured: true,
    cover: "/projects/prohr/1.png",
    learning: false,
    category: "FRONTEND",
    name: "ProHR (Prohor)",
    live_link: "https://staging.prohr.io/",
    associated_with: "REPLIQ Limited",
    client_code_link: "",
    server_code_link: "",
    doc_link: "",
    role: "Frontend Lead",
    tech_stack: [
      "Javascript",
      "NextJS v14.0",
      "TailwindCSS",
      "HeadlessUI",
      "MOBX",
      "Tanstack Query",
      "Formik",
      "yup",
      "twilio",
      "Vercel",
    ],
    details: {
      project_description:
        "A web application to make the job application and recruitment process easier for candidates and HRs respectively.",
      features: [
        "Organizations are added as a subdomain. Recruiters can login and setup their company profile. This profile can be shared publicly.",
        "The public links will have the organization page, the open jobs page and the job details page. To apply for a job, the candidate will need to login to the candidate side under the respective organization’s subdomain.",
        "Recruiters can post jobs, add video screening questions. The video screening test is a unique addition to save the time of initial interviews.",
        "Recruiters can review applicants per jobs, add notes, feedbacks, schedule interviews.",
        "Recruiters can also host interviews in the ProHR platform virtually via video calls developed using Twilio.",
        "Candidates upon login can setup profiles with dynamic information making job application processes easier.",
        "Candidates perform a video screening test which is a one-time, one-sided approach where questions appear on screen, and the candidates need to answer them in the video which is recorded. The recruiter sees how much time was allocated for a question and how much time the candidate took.",
        "Candidates can view application statuses, feedbacks from recruiters and attend video call interviews in the platform.",
        "Dynamic notification system using a diverse notification matrix.",
        "Admin panel for global tracking of jobs, interviews, organizations, applicants, and a resume bank with resume bulk upload feature,",
      ],
    },
  },
  {
    slug: "supplers",
    featured: true,
    learning: false,
    category: "FRONTEND",
    cover: "/projects/supplers/1.png",
    name: "Supplers",
    live_link: "https://staging.supplers.com/",
    associated_with: "REPLIQ Limited",
    client_code_link: "",
    server_code_link: "",
    doc_link: "",
    role: "Frontend Lead",
    tech_stack: [
      "Javascript",
      "NextJS v12.0",
      "TailwindCSS",
      "HeadlessUI",
      "MOBX",
      "Tanstack Query",
      "Formik",
      "yup",
      "Stripe",
      "Vercel",
    ],
    details: {
      project_description:
        "A simple banking application. A bank can have several types of accounts say current account, saving account, salary account etc. An account will have fields like name, number, creation date and balance etc. After starting the application, users will have 8 different choices as input from 1 to 8 through the console.",
      features: [
        "Create a new account",
        "Display all accounts",
        "Update an account",
        "Delete an account",
        "Deposit an amount into your account",
        "Withdraw an amount from your account",
        "Search for account",
        "Exit",
      ],
    },
  },
  {
    slug: "bookling",
    featured: true,
    learning: false,
    category: "FRONTEND",
    cover: "/projects/bookling.png",
    name: "Bookling",
    live_link: "https://bookling-nextjs.vercel.app/",
    associated_with: "none",
    client_code_link: "https://github.com/farhanhasindipro25/bookling-nextjs",
    server_code_link: "",
    doc_link: "",
    role: "Frontend Developer",
    tech_stack: [
      "Javascript",
      "ContextAPI",
      "NextJS v14.0",
      "TailwindCSS",
      "HeadlessUI",
      "FramerMotion",
      "Tanstack Query",
      "Formik",
      "yup",
      "Vercel",
    ],
    details: {
      project_description:
        "A simple banking application. A bank can have several types of accounts say current account, saving account, salary account etc. An account will have fields like name, number, creation date and balance etc. After starting the application, users will have 8 different choices as input from 1 to 8 through the console.",
      features: [
        "Create a new account",
        "Display all accounts",
        "Update an account",
        "Delete an account",
        "Deposit an amount into your account",
        "Withdraw an amount from your account",
        "Search for account",
        "Exit",
      ],
    },
  },
  {
    slug: "the-second-tune",
    featured: true,
    learning: true,
    category: "FULLSTACK",
    cover: "/projects/second-tune.png",
    name: "The Second Tune",
    live_link: "https://second-tune.web.app",
    associated_with: "none",
    client_code_link:
      "https://github.com/farhanhasindipro25/the-second-tune-client",
    server_code_link:
      "https://github.com/farhanhasindipro25/the-second-tune-server",
    doc_link: "",
    role: "Fullstack Developer",
    tech_stack: [
      "Javascript",
      "ContextAPI",
      "Firebase",
      "ReactJS",
      "TailwindCSS",
      "React Router DOM",
      "Tanstack Query",
      "React Hook Form",
      "ExpressJS",
      "MongoDB",
      "Stripe",
      "Vercel",
    ],
    details: {
      project_description:
        "A simple banking application. A bank can have several types of accounts say current account, saving account, salary account etc. An account will have fields like name, number, creation date and balance etc. After starting the application, users will have 8 different choices as input from 1 to 8 through the console.",
      features: [
        "Create a new account",
        "Display all accounts",
        "Update an account",
        "Delete an account",
        "Deposit an amount into your account",
        "Withdraw an amount from your account",
        "Search for account",
        "Exit",
      ],
    },
  },
];
