export const projects = [
  {
    slug: "pro-hr",
    name: "ProHR (Prohor)",
    live_link: "https://staging.prohr.io/",
    associated_with: "REPLIQ Limited",
    role: "Frontend Lead",
    tech_stack: [
      "Javascript",
      "NextJS v14.0",
      "TailwindCSS",
      "MOBX",
      "Tanstack Query",
      "Formik",
      "yup",
      "twilio",
    ],
  },
  {
    slug: "supplers",
    name: "Supplers",
    live_link: "https://staging.supplers.com/",
    associated_with: "REPLIQ Limited",
    role: "Frontend Lead",
    tech_stack: [
      "Javascript",
      "NextJS v12.0",
      "TailwindCSS",
      "MOBX",
      "Tanstack Query",
      "Formik",
      "yup",
      "Stripe",
    ],
  },
];
