export const projects = [
  {
    slug: "banking-console",
    featured: false,
    learning: true,
    name: "Console Banking Application",
    live_link: "",
    associated_with: "none",
    client_code_link: "",
    server_code_link:
      "https://github.com/farhanhasindipro25/banking-console-application-js",
    doc_link: "",
    role: "",
    tech_stack: ["Javascript", "OOP"],
    details: [],
  },
  {
    slug: "pro-hr",
    featured: true,
    learning: false,
    name: "ProHR (Prohor)",
    live_link: "https://staging.prohr.io/",
    associated_with: "REPLIQ Limited",
    client_code_link: "",
    server_code_link: "",
    doc_link: "",
    role: "Frontend Lead",
    tech_stack: [
      "Javascript",
      "NextJS v14.0",
      "TailwindCSS",
      "HeadlessUI",
      "MOBX",
      "Tanstack Query",
      "Formik",
      "yup",
      "twilio",
      "Vercel",
    ],
    details: [],
  },
  {
    slug: "supplers",
    featured: true,
    learning: false,
    name: "Supplers",
    live_link: "https://staging.supplers.com/",
    associated_with: "REPLIQ Limited",
    client_code_link: "",
    server_code_link: "",
    doc_link: "",
    role: "Frontend Lead",
    tech_stack: [
      "Javascript",
      "NextJS v12.0",
      "TailwindCSS",
      "HeadlessUI",
      "MOBX",
      "Tanstack Query",
      "Formik",
      "yup",
      "Stripe",
      "Vercel",
    ],
    details: [],
  },
  {
    slug: "bookling",
    featured: true,
    learning: false,
    name: "Bookling",
    live_link: "https://bookling-nextjs.vercel.app/",
    associated_with: "none",
    client_code_link: "https://github.com/farhanhasindipro25/bookling-nextjs",
    server_code_link: "",
    doc_link: "",
    role: "Frontend Developer",
    tech_stack: [
      "Javascript",
      "ContextAPI",
      "NextJS v14.0",
      "TailwindCSS",
      "HeadlessUI",
      "FramerMotion",
      "Tanstack Query",
      "Formik",
      "yup",
      "Vercel",
    ],
    details: [],
  },
  {
    slug: "the-second-tune",
    featured: true,
    learning: true,
    name: "The Second Tune",
    live_link: "https://second-tune.web.app",
    associated_with: "none",
    client_code_link:
      "https://github.com/farhanhasindipro25/the-second-tune-client",
    server_code_link:
      "https://github.com/farhanhasindipro25/the-second-tune-server",
    doc_link: "",
    role: "Fullstack Developer",
    tech_stack: [
      "Javascript",
      "ContextAPI",
      "Firebase",
      "ReactJS",
      "TailwindCSS",
      "React Router DOM",
      "Tanstack Query",
      "React Hook Form",
      "ExpressJS",
      "MongoDB",
      "Stripe",
      "Vercel",
    ],
    details: [],
  },
];
