export const featuredWorks = [
  {
    position: "UX Engineer",
    company: "Read Global Consultants",
    linkedin: "https://www.linkedin.com/company/read-global-consultant/",
    website: "https://www.readjobs.com/",
    start_date: "February 2024",
    end_date: "Present",
    company_type: "Staffing and Recruiting",
  },
  {
    position: "Junior Frontend Developer",
    company: "REPLIQ Limited",
    linkedin: "https://www.linkedin.com/company/repliqltd/",
    website: "https://www.repliq.dev/",
    start_date: "February 2023",
    end_date: "January 2024",
    company_type: "Information Technology",
  },
];

export const works = [
  {
    position: "UX Engineer",
    company: "Read Global Consultants",
    start_date: "February 2024",
    end_date: "Present",
    company_description: "Staffing and Recruiting",
    roles: [
      "Create visually appealing designs for UIs using Figma and TailwindCSS.",
      "Develop scalable design systems that maintain consistency in color schemes, typography, and iconography.",
      "Translate design wireframes or prototypes into interactive and functional interfaces.",
      "Use prototyping tools to build interactive models for user testing and feedback.",
      "Implement interactive elements, animations, and transitions to enhance overall user experience.",
      "Ensure the user interface is intuitive, engaging, and easy to navigate.",
      "Maintain branding consistency across all designs.",
      "Maintain Agile methodologies in the Software Development Lifecycle.",
      "Plan well-maintained sprints to ensure efficient development cycles.",
      "Utilize NextJS and TailwindCSS to build complex web application layouts, features, and functionalities.",
      "Integrate state management libraries such as MOBX/Redux.",
      "Integrate modern tools like Tanstack Query, Formik, YUP, React Hook Forms, Zod, etc., to optimize codebases.",
      "Maintain a scalable codebase following principles such as DRY, SOLID, and YAGNI.",
      "Implement and follow design patterns and architectures to ensure a structured and maintainable codebase.",
      "Maintain thorough documentation of the codebase for clarity and ease of understanding.",
      "Review designs based on requirement analysis and assist in setting up the backend payload.",
    ],
    skills: [
      "JavaScript",
      "ReactJS",
      "NextJS",
      "Tailwind CSS",
      "Redux",
      "GitHub",
      "Jira",
      "Figma",
      "Tanstack Query",
      "Axios",
      "clsx",
      "tw-merge",
      "class-variance-authority",
      "Headless UI",
      "TypeScript",
      "Slack",
    ],
  },
  {
    position: "Junior Frontend Developer",
    company: "REPLIQ Limited",
    start_date: "February 2023",
    end_date: "January 2024",
    company_description: "Information Technology",
    roles: [
      "Use NextJS and TailwindCSS to build complex layouts, features, and functionalities of Web Applications.",
      "Maintain and finalize data structure and field names from Figma designs for backend development.",
      "Build scalable and re-usable components using libraries like tw-merge, clsx, and class-variance-authority.",
      "Maintain kits for different scenarios to serve as a storage for utilities of different contexts. Example: StylesKit for repetitive stylings, HTTPKit for the Axios setup, UtilsKit for common reusable Javascript functions and APIKit containing a large object for all API call functions.",
      "Maintain clean approaches to forms and validations using Formik and YUP.",
      "Write well-structured and detailed documentation for all sorts of functionalities in the project’s codebase.",
      "Guide interns/trainees with training modules and maintaining task management for them.",
      "Take sessions for interns/trainees on various advances Javascript, React, TailwindCSS topics.",
      "Plan sprints based on client requirements via a poker session.",
      "Maintain agile software development methodologies through well defined scrums within the Software Development Lifecycle (SDLC).",
    ],
    skills: [
      "GitHub",
      "MobX",
      "JavaScript",
      "NextJS",
      "Tanstack Query",
      "ReactJS",
      "tw-merge",
      "class variance authority",
      "HeadlessUI",
      "ClickUp",
      "Figma",
      "clsx",
      "Twilio",
      "Tailwind CSS",
      "Vercel",
      "Stripe",
      "Microsoft Teams",
      "Headless UI",
    ],
  },
  {
    position: "Teacher's Assistant",
    company: "Department of Mathematics and Natural Sciences, BRAC University",
    start_date: "January 2022",
    end_date: "April 2022",
    company_description: "MAT 212",
    roles: [
      "Maintained and organized a slack channel for all the students of that semester.",
      "Edited videos of lectures provided by the course instructor.",
      "Uploaded lectures in buX (BRAC University X), the portal for having recorded lectures of departmental courses introduced during the COVID-19 pandemic.",
      "Made lecture notes and quiz questions in HTML, CSS, and LateX and uploaded them to buX.",
    ],
    skills: ["Slack", "LaTeX", "HTML", "Adobe Premiere Pro"],
  },
  {
    position: "Student Tutor",
    company: "Department of Mathematics and Natural Sciences, BRAC University",
    start_date: "June 2021",
    end_date: "September 2021",
    company_description: "MAT 215",
    roles: [
      "Helped students in understanding concepts of lectures.",
      "Took consultation sessions.",
    ],
    skills: ["Slack", "LaTeX"],
  },
  {
    position: "Creative Director",
    company: "BRACU Express",
    start_date: "October 2019",
    end_date: "August 2021",
    company_description:
      "An independent monthly publication by Brac University students.",
    roles: [
      "Pioneer for the idea of conceptual custom headers for the entertainment page.",
      "Briefed and overlooked the work of graphic designers.",
      "Overlooked at the creative outlook of social media posts.",
    ],
    skills: ["Adobe Illustrator", "Adobe Photoshop", "Adobe Premiere Pro"],
  },
];
